### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-friends#16]
I'm having a problem running `sbot server` in one terminal and `sbot createHistoryStream` in another. Based on the stack trace I'm thinking this may be a bug in ssb-friends, but I'm happy to move this elsewhere. I originally had this problem with `scuttlebot@13.0.3` and `ssb-friends@3.1.4`, but after upgrading with `npm -g install scuttlebot` I can confirm this is affecting `ssb-friends@3.1.6` as well.

```console
$ npm -g ls
/home/christianbundy/.node_modules/lib
├─┬ scuttlebot@13.0.3
│ └── ssb-friends@3.1.6 
└─┬ ssb-ebt@5.2.6 -> /home/christianbundy/src/ssbc/ssb-ebt
  └─┬ scuttlebot@10.5.2
    └── ssb-friends@2.4.0
```

```console
$ sbot server
scuttlebot 13.0.3 /home/christianbundy/.ssb logging.level:notice
my key ID: +oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519
ssb-friends: stream legacy api used
/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/ssb-friends/index.js:56
        if(g && opts.id !== id && g[opts.id] && g[opts.id][id] === -1) {
                     ^

TypeError: Cannot read property 'id' of undefined
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/ssb-friends/index.js:56:22
    at Object.onReady (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/layered-graph/index.js:81:22)
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/ssb-friends/index.js:54:15
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/pull-cont/source.js:18:5
    at next (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/pull-stream/sinks/drain.js:37:9)
    at sink (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:61:7)
    at Object.exports.pipeToStream (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/muxrpc/util.js:138:5)
    at PacketStreamSubstream.stream.read (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/muxrpc/stream.js:74:18)
    at PacketStream._onstream (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:228:11)
```

```console
$ sbot createHistoryStream
Exception thrown by PacketStream substream end handler Error: stream ended with:0 but wanted:34
    at drain (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:43:26)
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:63:18
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:114:13
    at drain (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:158:5)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Error: stream ended with:0 but wanted:34
    at drain (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:43:26)
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:63:18
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:114:13
    at drain (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/stream-to-pull-stream/index.js:158:5)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by christianbundy** [comment]
Same as https://github.com/ssbc/ssb-server/issues/608!
